// Mock data for CV - will be replaced with backend later
// Multi-language content (EN default, NO, TR)

export const personalInfo = {
  name: "Mehmet Zeki Oguz",
  initials: "MZO",
  email: "mzogz@hotmail.com",
  phone: "+47 45546080",
  location: "Trondheim, Norway",
  linkedin: "https://linkedin.com/in/zekiogz",
  github: "https://github.com/zekiogz",
  website: "cv.multilingual.no",
};

export const translations = {
  en: {
    nav: {
      about: "About",
      experience: "Experience",
      skills: "Skills",
      certifications: "Credentials",
      projects: "Projects",
      contact: "Contact",
    },
    hero: {
      kicker: "Available for remote engagements",
      role: "AI Agent Evaluation Specialist · Multilingual Systems Tester · Independent Builder",
      summary:
        "Remote-ready AI evaluation professional assessing agent output quality across 15+ structured domains — safety, factuality, coherence, translation and comparative ranking. I combine disciplined rubric-based review with hands-on experimentation in multi-model workflows and self-directed agent orchestration.",
      signals: ["rubric-check", "trace-review", "multi-model", "remote-async"],
      cta1: "Get in touch",
      cta2: "Download CV",
      scrollHint: "Scroll to explore",
    },
    about: {
      title: "About",
      kicker: "profile overview",
      body: [
        "I work at the intersection of language, evaluation, and emerging AI systems. For the last year, I've evaluated AI-generated responses across more than fifteen specialized domains — from safety and moderation to multilingual translation and comparative model ranking — producing the kind of structured, evidence-based feedback that directly feeds model training loops.",
        "In parallel, I prototype and stress-test multi-model agent workflows on real-world budgets. My goal is practical: understand how autonomous systems should actually be configured, adapted, and improved beyond rigid templates. I treat experimentation as a disciplined research loop, not hobbyist trial-and-error.",
        "Beyond evaluation, I bring a decade of professional translation and interpretation experience (Norwegian · Turkish · English · Swedish), which trained my instinct for ambiguity, context shift, and high-accountability review — all of which translate cleanly to agent trace analysis.",
      ],
      stats: [
        { value: "15+", label: "Evaluation domains" },
        { value: "7", label: "Languages spoken" },
        { value: "4+", label: "Years in QA & review" },
        { value: "100%", label: "Remote-first" },
      ],
    },
    experience: {
      title: "Experience",
      kicker: "professional track record",
      items: [
        {
          role: "AI Quality Rater",
          company: "Mindy-Support",
          type: "Freelance · Remote",
          period: "Dec 2024 — Present",
          bullets: [
            "Evaluate AI-generated responses using explicit criteria for safety, factuality, coherence, policy compliance, user-intent alignment and overall answer quality across 15+ specialized domains.",
            "Perform comparative ranking of multiple model outputs and provide structured written reasoning to support LLM training, preference learning and quality improvement cycles.",
            "Create detailed annotations in specialized evaluation tooling with emphasis on traceability, error categorization, consistency and guideline adherence.",
            "Review nuanced failure cases spanning safety & moderation, content understanding, visual content tasks, translation and domain-specific evaluations.",
            "Operate independently in remote project blocks while maintaining quality thresholds, rapid onboarding and disciplined execution.",
          ],
          tags: ["Evaluation", "Rubrics", "LLM training", "Multi-model"],
        },
        {
          role: "Independent AI Systems Research",
          company: "Self-Directed Projects",
          type: "Prototyping · Workflow Design",
          period: "2024 — Present",
          bullets: [
            "Designed and iterated on a natural-language-driven platform concept enabling non-technical users to create, configure, deploy and operate workflows through guided AI agent orchestration.",
            "Structured the vision around modular setup flows, reusable building blocks, deployment-readiness and operational oversight — reducing friction from idea to usable system.",
            "Tested multiple LLMs, agent patterns and tooling combinations under real free-tier and budget constraints, comparing prompt adherence, reliability, failure modes and practical execution limits.",
            "Committed recent project work to a more traceable GitHub-centered workflow so architecture decisions, iteration history and implementation progress can be preserved and reviewed.",
            "Treat experimentation as disciplined research — understanding how autonomous workflows should be configured safely and improved for real project use.",
          ],
          tags: ["Agents", "Orchestration", "Prompt eng.", "Systems"],
        },
        {
          role: "Turkish Translator & Interpreter",
          company: "Tolkenett",
          type: "Freelance · Norway",
          period: "Nov 2021 — Present",
          bullets: [
            "Deliver Norwegian–Turkish interpretation and translation across legal, medical and corporate contexts with high accuracy, confidentiality and contextual sensitivity.",
            "Verify terminology, factual consistency and source meaning under time pressure — strengthening judgment in ambiguity-heavy and high-accountability environments.",
            "Maintain structured note-taking, clarification habits and quality discipline directly transferable to agent trace review and failure analysis.",
          ],
          tags: ["Translation", "Legal", "Medical", "Quality"],
        },
      ],
    },
    skills: {
      title: "Core Capabilities",
      kicker: "what I bring",
      cards: [
        {
          title: "AI Agent Testing",
          desc: "Rubric-based assessment, edge-case review, multi-turn behavior evaluation, comparative output ranking and failure-pattern identification.",
          tags: ["Rubrics", "Pass/Fail", "Traces", "Edge cases"],
        },
        {
          title: "Technical Evaluation",
          desc: "Systems thinking around modular workflows, prompt-to-tool reliability, trace review, evidence-based feedback and deployment constraints.",
          tags: ["Workflows", "Reliability", "Prompts", "Architecture"],
        },
        {
          title: "Execution Discipline",
          desc: "Remote asynchronous delivery, self-directed learning, documentation-first iteration and growing GitHub traceability across independent projects.",
          tags: ["Async", "Docs-first", "GitHub", "Self-led"],
        },
        {
          title: "Language Advantage",
          desc: "Native Turkish, professional Norwegian, advanced English, fluent Swedish — plus additional multilingual exposure supporting localization and cross-context review.",
          tags: ["7 Languages", "Localization", "Cross-context"],
        },
      ],
      stackTitle: "Technical surface",
      stack: [
        "AI Agent Evaluation",
        "Rubric Design",
        "Failure Pattern Detection",
        "Multi-Turn Analysis",
        "Structured Feedback",
        "Preference Ranking",
        "Safety Review",
        "Factuality Verification",
        "Localization QA",
        "JavaScript",
        "React",
        "HTML5 / CSS3",
        "Git / GitHub",
        "VS Code",
        "Azure Fundamentals",
        "AWS Fundamentals",
      ],
    },
    certifications: {
      title: "Certifications",
      kicker: "validated domains",
      groups: [
        { name: "Safety & Moderation", items: ["AFM v3", "GM Safety"] },
        { name: "Content Understanding", items: ["CYU", "CYU News Topic"] },
        { name: "Visual Content", items: ["VCG TTI", "VCG Message", "VCG ADM", "VCG Genmoji"] },
        { name: "Translation & Proofreading", items: ["TA IP", "TA Proofreading"] },
        { name: "Domain-Specific", items: ["DE", "LE", "Ogma PR", "In-progress modules"] },
      ],
      trainingTitle: "Training & Learning",
      training: [
        "Front-End Web Development Certificate (self-paced)",
        "Generative AI fundamentals",
        "Azure Fundamentals track",
        "AWS Cloud Practitioner track",
      ],
    },
    languages: {
      title: "Languages",
      kicker: "communication surface",
      items: [
        { name: "English", level: "Professional", score: 88 },
        { name: "Norwegian", level: "Professional", score: 95 },
        { name: "Turkish", level: "Native / Community", score: 100 },
        { name: "Swedish", level: "Fluent", score: 80 },
        { name: "Kurdish", level: "Native / Community", score: 95 },
        { name: "German", level: "Intermediate", score: 55 },
        { name: "Arabic", level: "Basic conversational", score: 35 },
      ],
    },
    projects: {
      title: "Selected Projects",
      kicker: "applied experiments",
      items: [
        {
          name: "Agent Orchestration Platform (concept)",
          status: "Prototype · Ongoing",
          desc: "Natural-language-first platform concept enabling non-technical users to configure, deploy and operate multi-step agent workflows with guided setup and operational oversight.",
          tags: ["Agents", "NLP", "Orchestration", "UX"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Multi-Model Evaluation Harness",
          status: "Research · 2025",
          desc: "Comparative testing framework probing prompt adherence, reliability and failure modes across free-tier and budget-grade LLMs under realistic workloads.",
          tags: ["Evaluation", "LLMs", "Benchmarking"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Multilingual.no — Language Services Hub",
          status: "Live · 2025",
          desc: "Domain-based hub for multilingual services, translation resources and personal professional presence. This CV lives at cv.multilingual.no.",
          tags: ["Web", "Domain", "Branding"],
          link: "https://multilingual.no",
        },
      ],
    },
    contact: {
      title: "Let's connect",
      kicker: "open channel",
      intro:
        "I'm open to remote AI evaluation projects, multilingual QA roles and collaborative work on agent systems. Send a note — I reply within 24 hours.",
      form: {
        name: "Your name",
        email: "Email address",
        subject: "Subject",
        message: "Your message",
        submit: "Send message",
        sending: "Sending…",
        success: "Message received. I'll reply shortly.",
        error: "Something went off-signal. Try again.",
      },
    },
    footer: {
      tagline: "Built with care. Hosted on multilingual.no",
      rights: "All rights reserved.",
      focusMode: "Focus mode",
      standardView: "Standard view",
    },
  },
  no: {
    nav: {
      about: "Om meg",
      experience: "Erfaring",
      skills: "Ferdigheter",
      certifications: "Sertifiseringer",
      projects: "Prosjekter",
      contact: "Kontakt",
    },
    hero: {
      kicker: "Tilgjengelig for eksternt arbeid",
      role: "AI-evalueringsspesialist · Flerspråklig systemtester · Selvstendig utvikler",
      summary:
        "Erfaren AI-evaluator med vurdering av agentkvalitet på tvers av mer enn 15 strukturerte domener — sikkerhet, faktualitet, koherens, oversettelse og sammenlignende rangering. Jeg kombinerer disiplinert rubrikkbasert gjennomgang med praktisk eksperimentering innen fler-modell-arbeidsflyter og selvstyrt agent-orkestrering.",
      signals: ["rubrikksjekk", "spor-analyse", "fler-modell", "fjern-async"],
      cta1: "Ta kontakt",
      cta2: "Last ned CV",
      scrollHint: "Rull for å utforske",
    },
    about: {
      title: "Om meg",
      kicker: "profiloversikt",
      body: [
        "Jeg arbeider i krysningspunktet mellom språk, evaluering og nye AI-systemer. Det siste året har jeg vurdert AI-genererte svar på tvers av mer enn femten spesialiserte domener — fra sikkerhet og moderering til flerspråklig oversettelse og sammenlignende modellrangering.",
        "Parallelt prototyper og stress-tester jeg fler-modell agent-arbeidsflyter under reelle budsjettbegrensninger. Målet er praktisk: forstå hvordan autonome systemer faktisk bør konfigureres, tilpasses og forbedres utover stive maler.",
        "I tillegg til evaluering har jeg over ti års profesjonell oversetter- og tolkerfaring (norsk · tyrkisk · engelsk · svensk), noe som har trent instinktet mitt for tvetydighet, kontekstskifte og grundig kvalitetskontroll.",
      ],
      stats: [
        { value: "15+", label: "Evalueringsdomener" },
        { value: "7", label: "Språk behersket" },
        { value: "4+", label: "År med QA" },
        { value: "100%", label: "Fjernarbeid" },
      ],
    },
    experience: {
      title: "Erfaring",
      kicker: "profesjonell bakgrunn",
      items: [
        {
          role: "AI-kvalitetsvurderer",
          company: "Mindy-Support",
          type: "Frilans · Fjernarbeid",
          period: "Des 2024 — Nå",
          bullets: [
            "Vurderer AI-genererte svar basert på eksplisitte kriterier for sikkerhet, faktualitet, koherens, retningslinjer og brukerhensikt på tvers av 15+ spesialiserte domener.",
            "Utfører sammenlignende rangering av flere modellresultater med strukturert skriftlig begrunnelse for å støtte LLM-trening og preferanselæring.",
            "Lager detaljerte annotasjoner i spesialiserte evalueringsverktøy med vekt på sporbarhet, feilkategorisering og konsistens.",
            "Gjennomgår nyanserte feiltilfeller innen sikkerhet, innholdsforståelse, visuelt innhold, oversettelse og domenespesifikke evalueringer.",
            "Arbeider selvstendig i eksterne prosjektblokker med høye kvalitetskrav og disiplinert gjennomføring.",
          ],
          tags: ["Evaluering", "Rubrikker", "LLM-trening", "Fler-modell"],
        },
        {
          role: "Selvstendig AI-systemforskning",
          company: "Egne prosjekter",
          type: "Prototyping · Arbeidsflytdesign",
          period: "2024 — Nå",
          bullets: [
            "Designet og iterert et plattformkonsept drevet av naturlig språk som lar ikke-tekniske brukere konfigurere og drifte arbeidsflyter gjennom veiledet AI-agent-orkestrering.",
            "Strukturert visjonen rundt modulære oppsettsflyter, gjenbrukbare byggeklosser og operasjonell oversikt — for å redusere avstanden fra idé til brukbart system.",
            "Testet flere LLM-er, agent-mønstre og verktøy-kombinasjoner under reelle begrensninger, sammenlignet pålitelighet, feilmodi og praktiske grenser.",
            "Overført prosjektarbeid til en mer sporbar GitHub-sentrert arbeidsflyt slik at arkitekturbeslutninger og iterasjonshistorikk bevares.",
            "Behandler eksperimentering som disiplinert forskning — for å forstå hvordan autonome arbeidsflyter skal konfigureres trygt.",
          ],
          tags: ["Agenter", "Orkestrering", "Prompt", "Systemer"],
        },
        {
          role: "Tyrkisk tolk og oversetter",
          company: "Tolkenett",
          type: "Frilans · Norge",
          period: "Nov 2021 — Nå",
          bullets: [
            "Leverer norsk-tyrkisk tolking og oversettelse i juridiske, medisinske og bedriftsmessige sammenhenger med høy nøyaktighet og konfidensialitet.",
            "Verifiserer terminologi, faktuell konsistens og kildens mening under tidspress — styrker vurderingsevnen i tvetydige og ansvarskrevende miljøer.",
            "Opprettholder strukturert notatteknikk og kvalitetsdisiplin — direkte overførbart til agent-sporanalyse.",
          ],
          tags: ["Oversettelse", "Juridisk", "Medisinsk", "Kvalitet"],
        },
      ],
    },
    skills: {
      title: "Hovedferdigheter",
      kicker: "hva jeg bringer",
      cards: [
        {
          title: "AI-agenttesting",
          desc: "Rubrikkbasert vurdering, edge-case-analyse, fler-turnsevaluering, sammenlignende rangering og feilmønsteridentifikasjon.",
          tags: ["Rubrikker", "Pass/Fail", "Spor", "Edge-cases"],
        },
        {
          title: "Teknisk evaluering",
          desc: "Systemtenkning rundt modulære arbeidsflyter, prompt-til-verktøy-pålitelighet, sporgjennomgang og distribusjonsbegrensninger.",
          tags: ["Arbeidsflyt", "Pålitelighet", "Prompt", "Arkitektur"],
        },
        {
          title: "Gjennomføringsdisiplin",
          desc: "Asynkron fjernlevering, selvstyrt læring, dokumentasjonsførst-iterasjon og økende GitHub-sporbarhet.",
          tags: ["Async", "Docs", "GitHub", "Selvdrevet"],
        },
        {
          title: "Språkfordel",
          desc: "Tyrkisk som morsmål, profesjonelt norsk, avansert engelsk og flytende svensk — med ytterligere flerspråklig erfaring som støtter lokalisering.",
          tags: ["7 språk", "Lokalisering", "Kryss-kontekst"],
        },
      ],
      stackTitle: "Teknisk flate",
      stack: [
        "AI-agentevaluering",
        "Rubrikkdesign",
        "Feilmønsterdeteksjon",
        "Fler-turn-analyse",
        "Strukturert tilbakemelding",
        "Preferanserangering",
        "Sikkerhetsgjennomgang",
        "Faktaverifisering",
        "Lokaliserings-QA",
        "JavaScript",
        "React",
        "HTML5 / CSS3",
        "Git / GitHub",
        "VS Code",
        "Azure Fundamentals",
        "AWS Fundamentals",
      ],
    },
    certifications: {
      title: "Sertifiseringer",
      kicker: "validerte domener",
      groups: [
        { name: "Sikkerhet & moderering", items: ["AFM v3", "GM Safety"] },
        { name: "Innholdsforståelse", items: ["CYU", "CYU News Topic"] },
        { name: "Visuelt innhold", items: ["VCG TTI", "VCG Message", "VCG ADM", "VCG Genmoji"] },
        { name: "Oversettelse & korrektur", items: ["TA IP", "TA Proofreading"] },
        { name: "Domenespesifikke", items: ["DE", "LE", "Ogma PR", "Pågående moduler"] },
      ],
      trainingTitle: "Opplæring",
      training: [
        "Front-End webutviklingssertifikat (selvstudium)",
        "Generativ AI grunnleggende",
        "Azure Fundamentals",
        "AWS Cloud Practitioner",
      ],
    },
    languages: {
      title: "Språk",
      kicker: "kommunikasjonsflate",
      items: [
        { name: "Engelsk", level: "Profesjonelt", score: 88 },
        { name: "Norsk", level: "Profesjonelt", score: 95 },
        { name: "Tyrkisk", level: "Morsmål / miljø", score: 100 },
        { name: "Svensk", level: "Flytende", score: 80 },
        { name: "Kurdisk", level: "Morsmål / miljø", score: 95 },
        { name: "Tysk", level: "Middels", score: 55 },
        { name: "Arabisk", level: "Grunnleggende", score: 35 },
      ],
    },
    projects: {
      title: "Utvalgte prosjekter",
      kicker: "anvendt eksperimentering",
      items: [
        {
          name: "Agent-orkestreringsplattform (konsept)",
          status: "Prototype · Pågående",
          desc: "Plattformkonsept drevet av naturlig språk som lar ikke-tekniske brukere konfigurere og drifte flertrinns agent-arbeidsflyter.",
          tags: ["Agenter", "NLP", "Orkestrering", "UX"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Fler-modell evalueringsrammeverk",
          status: "Forskning · 2025",
          desc: "Sammenlignende testrammeverk som undersøker prompt-etterlevelse, pålitelighet og feilmodi på tvers av budsjett-LLM-er.",
          tags: ["Evaluering", "LLM-er", "Benchmark"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Multilingual.no — Språktjenester",
          status: "Live · 2025",
          desc: "Domenebasert knutepunkt for flerspråklige tjenester og profesjonell tilstedeværelse. CV-en ligger på cv.multilingual.no.",
          tags: ["Web", "Domene", "Branding"],
          link: "https://multilingual.no",
        },
      ],
    },
    contact: {
      title: "La oss snakke",
      kicker: "åpen kanal",
      intro:
        "Jeg er åpen for eksterne AI-evalueringsprosjekter, flerspråklige QA-roller og samarbeid om agent-systemer. Send en melding — jeg svarer innen 24 timer.",
      form: {
        name: "Ditt navn",
        email: "E-postadresse",
        subject: "Emne",
        message: "Din melding",
        submit: "Send melding",
        sending: "Sender…",
        success: "Melding mottatt. Jeg svarer snart.",
        error: "Noe gikk galt. Prøv igjen.",
      },
    },
    footer: {
      tagline: "Bygget med omtanke. Hostet på multilingual.no",
      rights: "Alle rettigheter forbeholdt.",
      focusMode: "Fokus-modus",
      standardView: "Standard visning",
    },
  },
  tr: {
    nav: {
      about: "Hakkımda",
      experience: "Deneyim",
      skills: "Yetenekler",
      certifications: "Sertifikalar",
      projects: "Projeler",
      contact: "İletişim",
    },
    hero: {
      kicker: "Uzaktan projelere hazır",
      role: "AI Ajan Değerlendirme Uzmanı · Çok Dilli Sistem Test Uzmanı · Bağımsız Geliştirici",
      summary:
        "15+ yapılandırılmış alanda AI çıktı kalitesini değerlendiren uzaktan çalışmaya hazır bir AI değerlendirme profesyoneliyim — güvenlik, olgusal doğruluk, tutarlılık, çeviri ve karşılaştırmalı sıralama. Disiplinli rubrik tabanlı inceleme ile çoklu model iş akışlarındaki pratik deneyimi birleştiriyorum.",
      signals: ["rubrik-kontrol", "iz-inceleme", "coklu-model", "uzak-async"],
      cta1: "İletişime geç",
      cta2: "CV indir",
      scrollHint: "Keşfetmek için kaydır",
    },
    about: {
      title: "Hakkımda",
      kicker: "profil özeti",
      body: [
        "Dil, değerlendirme ve gelişen AI sistemlerinin kesişiminde çalışıyorum. Son bir yılda, güvenlik ve moderasyondan çok dilli çeviriye ve karşılaştırmalı model sıralamasına kadar on beşten fazla özel alanda AI tarafından üretilen yanıtları değerlendirdim.",
        "Paralel olarak, gerçek dünya bütçe kısıtlamaları altında çoklu model ajan iş akışlarını prototipliyor ve stres testinden geçiriyorum. Amacım pratik: otonom sistemlerin gerçekte nasıl yapılandırılması, uyarlanması ve iyileştirilmesi gerektiğini anlamak.",
        "Değerlendirmenin ötesinde, on yıllık profesyonel çeviri ve tercümanlık deneyimim (Norveççe · Türkçe · İngilizce · İsveççe) var — bu deneyim, belirsizlik, bağlam değişimi ve yüksek hesap verebilirlikli inceleme içgüdümü eğitti.",
      ],
      stats: [
        { value: "15+", label: "Değerlendirme alanı" },
        { value: "7", label: "Konuştuğum dil" },
        { value: "4+", label: "QA yılı" },
        { value: "100%", label: "Uzaktan çalışma" },
      ],
    },
    experience: {
      title: "Deneyim",
      kicker: "profesyonel geçmiş",
      items: [
        {
          role: "AI Kalite Değerlendiricisi",
          company: "Mindy-Support",
          type: "Freelance · Uzaktan",
          period: "Ara 2024 — Günümüz",
          bullets: [
            "15+ özel alanda güvenlik, olgusal doğruluk, tutarlılık, politika uyumu, kullanıcı niyeti hizalaması ve genel yanıt kalitesi için açık kriterler kullanarak AI üretimli yanıtları değerlendiriyorum.",
            "LLM eğitimi, tercih öğrenmesi ve kalite iyileştirme döngülerini desteklemek için birden fazla model çıktısının karşılaştırmalı sıralamasını yapıyor ve yapılandırılmış yazılı gerekçe sağlıyorum.",
            "İzlenebilirlik, hata kategorizasyonu, tutarlılık ve kılavuz uyumuna vurgu ile özel değerlendirme araçlarında ayrıntılı açıklamalar oluşturuyorum.",
            "Güvenlik, içerik anlama, görsel içerik görevleri, çeviri ve alana özgü değerlendirmelere yayılan nüanslı hata vakalarını inceliyorum.",
            "Kalite eşiklerini, hızlı adaptasyonu ve disiplinli yürütmeyi korurken uzaktan proje bloklarında bağımsız çalışıyorum.",
          ],
          tags: ["Değerlendirme", "Rubrikler", "LLM eğitimi", "Çoklu model"],
        },
        {
          role: "Bağımsız AI Sistem Araştırması",
          company: "Kişisel Projeler",
          type: "Prototipleme · İş Akışı Tasarımı",
          period: "2024 — Günümüz",
          bullets: [
            "Teknik olmayan kullanıcıların rehberli AI ajan orkestrasyonu ile iş akışları oluşturmasını, yapılandırmasını ve dağıtmasını sağlayan doğal dil odaklı bir platform konsepti tasarladım ve iteratif olarak geliştirdim.",
            "Vizyonu modüler kurulum akışları, yeniden kullanılabilir yapı taşları ve operasyonel gözetim etrafında yapılandırarak fikirden kullanılabilir sisteme geçişi kolaylaştırdım.",
            "Gerçek ücretsiz katman ve bütçe kısıtlamaları altında çoklu LLM, ajan desenleri ve araç kombinasyonları test ettim; prompt uyumu, güvenilirlik ve başarısızlık modlarını karşılaştırdım.",
            "Son proje çalışmalarımı mimari kararların ve iterasyon geçmişinin korunabileceği daha izlenebilir bir GitHub merkezli iş akışına taşıdım.",
            "Deneyi hobi düzeyinde bir deneme-yanılma olarak değil, otonom iş akışlarının güvenli biçimde yapılandırılmasını anlamak için disiplinli bir araştırma olarak ele alıyorum.",
          ],
          tags: ["Ajanlar", "Orkestrasyon", "Prompt", "Sistemler"],
        },
        {
          role: "Türkçe Çevirmen ve Tercüman",
          company: "Tolkenett",
          type: "Freelance · Norveç",
          period: "Kas 2021 — Günümüz",
          bullets: [
            "Hukuki, tıbbi ve kurumsal bağlamlarda yüksek doğruluk, gizlilik ve bağlamsal hassasiyetle Norveççe-Türkçe tercümanlık ve çeviri hizmeti sunuyorum.",
            "Zaman baskısı altında terminoloji, olgusal tutarlılık ve kaynak anlamını doğrulayarak belirsizlik yoğun ortamlardaki muhakemeyi güçlendiriyorum.",
            "Doğrudan ajan iz incelemesine ve hata analizine aktarılabilen yapılandırılmış not alma ve kalite disiplini sürdürüyorum.",
          ],
          tags: ["Çeviri", "Hukuk", "Tıp", "Kalite"],
        },
      ],
    },
    skills: {
      title: "Temel Yetkinlikler",
      kicker: "neler sunuyorum",
      cards: [
        {
          title: "AI Ajan Testi",
          desc: "Rubrik tabanlı değerlendirme, kenar vaka incelemesi, çok turlu davranış analizi, karşılaştırmalı sıralama ve hata deseni tespiti.",
          tags: ["Rubrikler", "Geçer/Kalır", "İzler", "Kenar vakalar"],
        },
        {
          title: "Teknik Değerlendirme",
          desc: "Modüler iş akışları, prompt-araç güvenilirliği, iz incelemesi ve dağıtım kısıtlamaları etrafında sistemsel düşünce.",
          tags: ["İş akışı", "Güvenilirlik", "Prompt", "Mimari"],
        },
        {
          title: "Yürütme Disiplini",
          desc: "Uzaktan asenkron teslimat, kendi kendine öğrenme, dokümantasyon öncelikli iterasyon ve artan GitHub izlenebilirliği.",
          tags: ["Async", "Docs", "GitHub", "Öz-yönetim"],
        },
        {
          title: "Dil Avantajı",
          desc: "Ana dil Türkçe, profesyonel Norveççe, ileri İngilizce, akıcı İsveççe — yerelleştirme ve çapraz bağlam incelemesini destekleyen ek çok dilli deneyim.",
          tags: ["7 dil", "Yerelleştirme", "Çapraz bağlam"],
        },
      ],
      stackTitle: "Teknik yüzey",
      stack: [
        "AI Ajan Değerlendirmesi",
        "Rubrik Tasarımı",
        "Hata Deseni Tespiti",
        "Çok Turlu Analiz",
        "Yapılandırılmış Geri Bildirim",
        "Tercih Sıralaması",
        "Güvenlik İncelemesi",
        "Olgu Doğrulama",
        "Yerelleştirme QA",
        "JavaScript",
        "React",
        "HTML5 / CSS3",
        "Git / GitHub",
        "VS Code",
        "Azure Fundamentals",
        "AWS Fundamentals",
      ],
    },
    certifications: {
      title: "Sertifikalar",
      kicker: "doğrulanmış alanlar",
      groups: [
        { name: "Güvenlik & Moderasyon", items: ["AFM v3", "GM Safety"] },
        { name: "İçerik Anlama", items: ["CYU", "CYU News Topic"] },
        { name: "Görsel İçerik", items: ["VCG TTI", "VCG Message", "VCG ADM", "VCG Genmoji"] },
        { name: "Çeviri & Redaksiyon", items: ["TA IP", "TA Proofreading"] },
        { name: "Alana Özgü", items: ["DE", "LE", "Ogma PR", "Devam eden modüller"] },
      ],
      trainingTitle: "Eğitim & Öğrenim",
      training: [
        "Front-End Web Geliştirme Sertifikası (kendi hızında)",
        "Üretken AI temelleri",
        "Azure Fundamentals",
        "AWS Cloud Practitioner",
      ],
    },
    languages: {
      title: "Diller",
      kicker: "iletişim yüzeyi",
      items: [
        { name: "İngilizce", level: "Profesyonel", score: 88 },
        { name: "Norveççe", level: "Profesyonel", score: 95 },
        { name: "Türkçe", level: "Ana dil / topluluk", score: 100 },
        { name: "İsveççe", level: "Akıcı", score: 80 },
        { name: "Kürtçe", level: "Ana dil / topluluk", score: 95 },
        { name: "Almanca", level: "Orta", score: 55 },
        { name: "Arapça", level: "Temel", score: 35 },
      ],
    },
    projects: {
      title: "Seçilmiş Projeler",
      kicker: "uygulamalı deneyler",
      items: [
        {
          name: "Ajan Orkestrasyon Platformu (konsept)",
          status: "Prototip · Devam ediyor",
          desc: "Teknik olmayan kullanıcıların çok adımlı ajan iş akışlarını yapılandırıp dağıtmasını sağlayan doğal dil odaklı platform konsepti.",
          tags: ["Ajanlar", "NLP", "Orkestrasyon", "UX"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Çoklu Model Değerlendirme Çatısı",
          status: "Araştırma · 2025",
          desc: "Bütçe LLM'lerinde prompt uyumu, güvenilirlik ve hata modlarını inceleyen karşılaştırmalı test çatısı.",
          tags: ["Değerlendirme", "LLM", "Benchmark"],
          link: "https://github.com/zekiogz",
        },
        {
          name: "Multilingual.no — Dil Hizmetleri Merkezi",
          status: "Canlı · 2025",
          desc: "Çok dilli hizmetler ve profesyonel varlık için alan adı tabanlı merkez. Bu CV cv.multilingual.no adresinde yaşıyor.",
          tags: ["Web", "Domain", "Branding"],
          link: "https://multilingual.no",
        },
      ],
    },
    contact: {
      title: "İletişime geçelim",
      kicker: "açık kanal",
      intro:
        "Uzaktan AI değerlendirme projelerine, çok dilli QA rollerine ve ajan sistemleri üzerine iş birliğine açığım. Bir not gönderin — 24 saat içinde yanıtlarım.",
      form: {
        name: "Adınız",
        email: "E-posta adresi",
        subject: "Konu",
        message: "Mesajınız",
        submit: "Mesaj gönder",
        sending: "Gönderiliyor…",
        success: "Mesaj alındı. Kısa sürede yanıtlayacağım.",
        error: "Bir şeyler ters gitti. Tekrar deneyin.",
      },
    },
    footer: {
      tagline: "Özenle inşa edildi. multilingual.no üzerinde barındırılıyor",
      rights: "Tüm hakları saklıdır.",
      focusMode: "Odak modu",
      standardView: "Standart görünüm",
    },
  },
};

export const languagesList = [
  { code: "en", label: "EN", name: "English" },
  { code: "no", label: "NO", name: "Norsk" },
  { code: "tr", label: "TR", name: "Türkçe" },
];
